services:
  postgres:
    image: 'postgres:17.5'
    environment:
      - 'POSTGRES_DB=sentimentapi'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432'
